# Sonoff S31 socket with TV, cable box, and sound system.
- platform: mqtt
  name: Entertainment Center Voltage
  state_topic: "tele/Entertainment_Center_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"
- platform: mqtt
  name: Entertainment Center Current
  state_topic: "tele/Entertainment_Center_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A"
- platform: mqtt
  name: Entertainment Center Power
  state_topic: "tele/Entertainment_Center_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"
- platform: mqtt
  name: Entertainment Center Energy Today
  state_topic: "tele/Entertainment_Center_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: Entertainment Center Energy Yesterday
  state_topic: "tele/Entertainment_Center_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: Entertainment Center Energy Total
  state_topic: "tele/Entertainment_Center_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kWh"
# Sonoff S31 socket with PS4, Wii U, and Raspberry Pi (HA)
- platform: mqtt
  name: Game Console Voltage
  state_topic: "tele/Gaming_And_Media_PC_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"
- platform: mqtt
  name: Game Console Current
  state_topic: "tele/Gaming_And_Media_PC_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A"
- platform: mqtt
  name: Game Console Power
  state_topic: "tele/Gaming_And_Media_PC_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"
- platform: mqtt
  name: Game Console Energy Today
  state_topic: "tele/Gaming_And_Media_PC_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: Game Console Energy Yesterday
  state_topic: "tele/Gaming_And_Media_PC_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: Game Console Energy Total
  state_topic: "tele/Gaming_And_Media_PC_Socket/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kWh"